name: CI/CD - Login Tests

on:
  workflow_dispatch:

jobs:
  Windows_Test: # Name of first job
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code  #My project
        uses: actions/checkout@v4

      - name: Setup JDK 21  
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven  #to be able to run mvn commands
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn -DbrowserName="edge" -DheadlessExecution="false" -Dtest="login.tests.LoginTestCases" test
        

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

